### PR TITLE
[DSET-4151] Migrate from git submodules to subtrees

### PR DESCRIPTION
**Pull request by tomaz-s1**
## Description

This pull request migrates vendored dependencies (`dataset-go`, `opentelemetry-collector-contrib`, `opentelemetry-collector-releaes`, `scalyr-opentelemetry-collector-contrib`) from git submodules to git subtrees.

## Background, Context

codecov doesn't support reporting and tracking coverage for submodules (e.g. https://app.codecov.io/gh/scalyr/opentelemetry-exporter-dataset/commit/e0c5b9c394536d4753e555552a27d3d192e49e77), but hopefully it will work with subtrees.

In addition to that, I personally almost always prefer subtrees over submodules since they make make managing those dependencies easier and the end developer experience better (no need to manually check out additional things).

Only advantage of submodules is reducing the main repo size and initial repo check out in case some of the submodules are optional and not always checked out. In our case, all those dependencies are mandatory and need to be checked out for things to work.

This means that there is no benefit in terms of a faster initial clone / checkout since those dependencies need to be checked out regardless (as part of the main repo clone / checkout when using subtrees or as part of separate submodule checkout when using submodules).

### CODE REVIEW

**Comment by tomaz-s1** [comment]
codecov code coverage tracking and reporting is now indeed working - https://app.codecov.io/github/scalyr/opentelemetry-exporter-dataset/pull/11/tree 🎉 

It also required small fix to the pre-commit exclude patterns (767fadeef6da096702175700e87b0cceb203a857) - this issue was not caught with submodules setup in the past since pre-commit didn't have access to the submodules so it didn't try to scan files in there.

**Comment by tomaz-s1** [comment]
I noticed go dependency cache was also not working correctly since invalid paths were used so I tried to fix that as well - 78adba5ccbcb1216054a29eeaa1b6b70b0e177a9.

I confirmed the caching is now working correctly.

Before (https://github.com/scalyr/opentelemetry-exporter-dataset/actions/runs/5973915234/job/16207084163):

Screenshot 2023-08-25 at 10 57 31

After (https://github.com/scalyr/opentelemetry-exporter-dataset/actions/runs/5973940486/job/16207161608):

Screenshot 2023-08-25 at 10 57 52

**Comment by tomaz-s1** [comment]
Since the diff is large because of the added subtrees, here are the main commits to review:

* bc2cad861c16ed580559214b449275138617bc2a
* 0a9fe8f824009b8143a6ccf489a83660b67ec3d5
* 3a15ab101d3912cd8f727a23cf0a1c76027f78d5
* 767fadeef6da096702175700e87b0cceb203a857
* 78adba5ccbcb1216054a29eeaa1b6b70b0e177a9
* e8a209c1a070a6520d3cfcd00ec3fb98e9baf553
* a0f89d7ef82cf174634ac0a52b520ccf1bc6b5e4

**Review by martin-majlis-s1 — APPROVED** [review]
Awesome :)

**Pull request merged**
